### ISSUE TITLE
When installing Cloudflare-Warp, it does not install to scoop folder by default

### ISSUE THREAD

**Issue by TechPro424** [StarsbySea/ocean#4]
When installing Cloudflare-Warp, it does not install to scoop folder by default the way most scoop apps do, but instead installs to windows programs list, which I do not want. How do I make it install to scoop folder?

**Comment by StarsbySea** [comment]
Sorry for taking so long to get back to you.
I have tried a few things when creating this profile at the time, but it seems that the software still gets installed into the default C drive directory.
Also, because Cloudflare WARP installs the web filtering driver, it (I think) has to go through the software's own installer to make the software work properly.
It is also inferred from the fact that the installation requires administrator rights that the software is not portable.
Do you have any way of getting the software to install in the scoop directory, feel free to pull requests.
Perhaps I should state in the configuration file that the software is not portable and will be installed to the default directory, do you have any comments on this?

**Comment by TechPro424** [comment]
No comments
(I sound like a VIP in front of reporters lol)

**Comment by StarsbySea** [comment]
I'm just glad that someone other than me is using this repository and maybe it will be helpful to others.
We'll close this issue for now then and we'll communicate if there are any new updates.
